- hosts: all
  connection: local
  hosts: localhost
  no_log: false
  vars:
    server: localhost
    endpoint: 23.88.32.56
    algo_provider: local
    server_name: algo
    algo_server_name: algo
    IP_subject_alt_name: wizznet    
    ansible_ssh_port: 22 
    algo_ondemand_cellular: false
    algo_ondemand_wifi: false
    algo_store_pki: false
  vars_files:
    - config.cfg  
  tasks:
    - import_role:
        name: jumphost/common
      tags: [common]
    - import_role:
        name: jumphost/dns
      tags: [dns]
    - import_role:
        name: jumphost/local
      tags: [local]
    - import_role:
        name: jumphost/ssh_tunneling
      tags: [ssh_tunneling]
    - import_role:
        name: jumphost/wireguard
      tags: [wireguard]
