- hosts: all
  connection: local
  hosts: localhost
  no_log: false
  tasks:
    - import_role:
        name: fileserver
      tags: [fileserver]
    - import_role:
        name: mountfolders
      tags: [mountfolders]